### ISSUE TITLE
KeyError: 'filepath' - run the sample train failed & Sample evaluation result log is empty 

### ISSUE THREAD

**Issue by zxjia2002** [google-research/composed_image_retrieval#11]
@kihyuks @ksaito-ut 
Hi! I tried running the train sample, but I got the errors as follows:

```
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/CIR_Lab/composed_image_retrieval/src/main.py", line 126, in main_worker
    data = get_data(args, (preprocess_train, preprocess_val))
  File "/home/CIR_Lab/composed_image_retrieval/src/data.py", line 577, in get_data
    data["train"] = get_dataset_fn(args.train_data, args.dataset_type)(
  File "/home/CIR_Lab/composed_image_retrieval/src/data.py", line 473, in get_csv_dataset
    dataset = CsvDataset(
  File "/home/CIR_Lab/composed_image_retrieval/src/data.py", line 377, in __init__
    self.images = df[img_key].tolist()
  File "/home/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'filepath'
```

I have some questions:
- 'filepath' seems to be **args.csv_img_key** 's  default parameter. Should I specify it or not? 
- Should I **extract** the jpg images **one by one** from the tar archive in **cc3m download by img2dataset** ,add the path information of the images to the original **tsv** file and change it to **csv** file ?
- I also tried running the evaluation code, but after got **evaluation done**, the log folder is empty. Is this normal? Where should I see the results?

**Comment by zy1879046** [comment]
> @kihyuks @ksaito-ut Hi! I tried running the train sample, but I got the errors as follows:
> 
> ```
> Traceback (most recent call last):
>   File "/home/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>     fn(i, *args)
>   File "/home/CIR_Lab/composed_image_retrieval/src/main.py", line 126, in main_worker
>     data = get_data(args, (preprocess_train, preprocess_val))
>   File "/home/CIR_Lab/composed_image_retrieval/src/data.py", line 577, in get_data
>     data["train"] = get_dataset_fn(args.train_data, args.dataset_type)(
>   File "/home/CIR_Lab/composed_image_retrieval/src/data.py", line 473, in get_csv_dataset
>     dataset = CsvDataset(
>   File "/home/CIR_Lab/composed_image_retrieval/src/data.py", line 377, in __init__
>     self.images = df[img_key].tolist()
>   File "/home/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 3807, in __getitem__
>     indexer = self.columns.get_loc(key)
>   File "/home/anaconda3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
>     raise KeyError(key) from err
> KeyError: 'filepath'
> ```
> 
> I have some questions:
> 
> * 'filepath' seems to be **args.csv_img_key** 's  default parameter. Should I specify it or not?
> * Should I **extract** the jpg images **one by one** from the tar archive in **cc3m download by img2dataset** ,add the path information of the images to the original **tsv** file and change it to **csv** file ?
> * I also tried running the evaluation code, but after got **evaluation done**, the log folder is empty. Is this normal? Where should I see the results?

Hi,

I met the same problem, could you please tell me how it was solved? Thanks

**Comment by yzrs** [comment]
Hi, @KeepAndWin   @zy1879046  @kihyuks @ksaito-ut ,I met the same problem.The '**filepath**' refers to the column name of the images path column in csv file. However, there are only captions and urls in **Train_GCC-training.tsv** and **Validation_GCC-1.1.0-Validation.tsv**. Data downloaded by img2dataset is parquet, tar and json format. What should I do to solve this problem?I'm looking forward to your reply.

**Comment by caoziyang1997** [comment]
can you give me file about Train_GCC-training_output.csv and
Validation_GCC-1.1.0-Validation_output.csv! Thank you!
